name: Release

on:
  release:
    types:
      - published

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Export release metadata
        shell: bash
        run: |
          echo "SITEMAP_LASTMOD=${{ github.event.release.published_at }}" >> "${GITHUB_ENV}"

      - name: Publish repository release
        uses: tanaabased/actions/publish-repo@v1
        with:
          commands: |
            bun install --frozen-lockfile --ignore-scripts
            bun run lint
            bun run build
            version-injector dist/brewgen.sh --style sh --version "${{ github.event.release.tag_name }}"
          sync-token: ${{ secrets.TANAAB_COAXIUM_INJECTOR }}
